#https://www.mkdocs.org/user-guide/configuration/#
site_name: HEAL Platform Documentation
site_url: https://norc-heal.github.io/heal-data-pkg-guidance
repo_url: https://github.com/norc-heal/heal-data-pkg-guidance
nav:
  - Home: index.md
  - Introduction:
    - intro/index.md
    - Study-level metadata: intro/slmd.md
    - File-level metadata: intro/flmd.md
  - Deciding how you will share and document your data:
    - Are you early in collection/production of study artefacts?: section3/dec.md
    - Early in your study: section3/dec/early.md
    - Late in your study: 
        - Late in your study: section3/dec/late/index.md
        - Small number of artefacts or interested in high levels of transparency: section3/dec/late/small.md
        - Large number of artefacts or interested in implementing mandated levels of transparency only: section3/dec/late/large.md
    - Data Sharing Orientation: 
      - What is your data sharing orientation?: section3/orient/orient.md
      - Results-support: section3/orient/resultsupp.md
  - Terms & Concepts: 
    - Terms & Concepts: terms/index.md
    - File Types: terms/files.md
    - Holistic vs. Minimal Annotation: terms/holmin.md
    - Add-as-you-go vs. Top-down Annotation: terms/addtop.md
    - HEAL recommendations for organization and naming of study artefacts: terms/name.md
    - Data sharing orientations: terms/sharing.md
    - Study-level Metadata:
      - Resource Tracker: terms/studylevel/resource.md
      - Experiment Tracker: terms/studylevel/exp.md
    - File-level Metadata: terms/filelevel.md
    - Documenting dependencies: terms/depend.md


theme:
  name: material
  palette:
    scheme: heal_platform
  font:
    text: Montserrat
  logo: assets/HEAL_Initiative_White-cropped.svg
  features:
    - navigation.indexes
    # Disable for now, as it causes problems with links to sections in Safari
    # https://github.com/squidfunk/mkdocs-material/issues/3797
    # - navigation.instant
    - navigation.indexes
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.tracking
    #- navigation.sections
    #- toc.integrate
  favicon: assets/heal_logo.png
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://github.com/norc-heal
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mkdocs-video:
      is_video: True

# TODO: add footer (this may be included in the custom jinja template?)
#    [![](img/gen3.png)](https://ctds.uchicago.edu/gen3)[![](img/createdby.png)](https://ctds.uchicago.edu/)
#   [![image alt text](image URL link)](anchor link)

# function readMore() { var dots = document.getElementById("dots"); var moreText = document.getElementById("more"); var btnText = document.getElementById("read-more-btn"); var btnText = document.getElementById("read-more-explorer"); if (dots.style.display === "none") { dots.style.display = "inline"; btnText.innerHTML = "Read more"; moreText.style.display = "none"; } else { dots.style.display = "none"; btnText.innerHTML = "Read less"; moreText.style.display = "inline"; } }
