name: sync-healdata-utils
env:
  # input_<var> where you are syncing from (e.g., healdata-utils)
  # output_<var> where you are syncing to (ie in this repo)
  input_fork: norc-heal
  input_branch: pr-integration
  input_csv_docs_path: docs/schemas/csv-fields.md
  input_json_docs_path: docs/schemas/json-data-dictionary.md
  output_csv_docs_path: docs/schemas/csv-fields.md
  output_json_docs_path: docs/schemas/json-data-dictionary.md
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    name: Sync VLMD schemas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' 
      - name: Install dependencies
        run: pip install requests
      - name: Sync VLMD schemas
        run: python scripts/sync_schemas.py --fork ${input_fork} --branch ${input_branch} \
         --input-csv-docs-path ${input_csv_docs_path} --input-json-docs-path ${input_json_docs_path} \
         --output-csv-docs-path ${output_csv_docs_path} --output-json-docs-path ${output_json_docs_path}
      - name: Commit new files
        run: |
          git config user.name ${{ github.triggering_actor }}
          git config user.email ${{ github.triggering_actor }}@users.noreply.github.com
          git checkout -b update/healdata-utils-schemas
          git add ${json_docs_path} ${csv_docs_path}
          git commit -m "Automated update of rendered vlmd schemas in markdown"
          git push -u origin 

